trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  BASE_URL: 'https://automationexercise.com'
  LOGIN_EMAIL: 'testautomationmoufid@gmail.com'
  LOGIN_PASSWORD: 'Zakaria2026'
  CI: 'true'

steps:
  # 1. Installation propre de Node.js 20
  - task: NodeTool@1
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js environment v20'

  # 2. Installation des dépendances
  - script: |
      npm install
    displayName: 'Install npm dependencies packages'

  # 3. Utilisation du chemin direct pour installer les navigateurs
  - script: |
      sudo ./node_modules/.bin/playwright install --with-deps
    displayName: 'Fetch browser binaries'

  # 4. FIX : Exécution en utilisant le binaire local direct pour ignorer le vieux Node global
  - script: |
      ./node_modules/.bin/playwright test
    env:
      BASE_URL: $(BASE_URL)
      LOGIN_EMAIL: $(LOGIN_EMAIL)
      LOGIN_PASSWORD: $(LOGIN_PASSWORD)
      CI: $(CI)
    displayName: 'Execute Playwright end-to-end tests'

  # 5. Publication JUnit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/playwright-report/results.xml'
    condition: always()
    displayName: 'Publish JUnit XML metrics reports'

  # 6. Archivage HTML
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'playwright-report'
      artifact: 'playwright-report'
      publishLocation: 'pipeline'
    condition: always()
    displayName: 'Archive Playwright HTML report output bundles'