trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Vos variables d'environnement pour le projet
  BASE_URL: 'https://automationexercise.com'
  LOGIN_EMAIL: 'testautomationmoufid@gmail.com'
  LOGIN_PASSWORD: 'Zakaria2026'
  CI: 'true'

steps:
  # Bloc unique pour verrouiller la version Node 20 et tout exécuter à la suite
  - script: |
      # 1. Charger NVM (Node Version Manager) et installer Node.js 20
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install 20
      nvm use 20
      
      echo "=== VERIFICATION VERSION NODE ==="
      node -v
      echo "================================="

      # 2. Installer les packages du projet
      npm install

      # 3. Installer les navigateurs Playwright et les dépendances Linux (Sudo)
      sudo ./node_modules/.bin/playwright install --with-deps

      # 4. Lancer les tests de bout en bout
      ./node_modules/.bin/playwright test
    env:
      BASE_URL: $(BASE_URL)
      LOGIN_EMAIL: $(LOGIN_EMAIL)
      LOGIN_PASSWORD: $(LOGIN_PASSWORD)
      CI: $(CI)
    displayName: 'Setup Environment and Run Playwright Tests'

  # Étape de publication des résultats de tests XML (JUnit)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/playwright-report/results.xml'
    condition: always()
    displayName: 'Publish JUnit XML metrics reports'

  # Étape d'archivage du rapport HTML complet de Playwright
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'playwright-report'
      artifact: 'playwright-report'
      publishLocation: 'pipeline'
    condition: always()
    displayName: 'Archive Playwright HTML report output bundles'